### ISSUE TITLE
Icarus 'assign' statements don't work

### ISSUE THREAD

**Issue by jeremyherbert** [potentialventures/cocotb#209] opened 2015-02-06 21:39 UTC
Probably related to #96 .

http://www.edaplayground.com/x/4nt
http://www.edaplayground.com/x/96k

Given a very simple and (apparently) identical testbench written in verilog and in python, the output is different if there is an 'assign' style asynchronous assignment. Run the code and look at the EPWave window to see the output.

Can someone please run these under a non-icarus simulator to see if the problem is in icarus or in cocotb?

**Comment by chiggs** [comment] 2015-02-06 22:04
I need to check in more detail, there is a bug in Icarus which is fixed in newer versions which meant that values assigned outside of a process weren't updated.

**Comment by chiggs** [comment] 2015-02-06 22:14
I can confirm this works on Modelsim and Riviera so it is the Icarus bug.

You could try either compiling the latest version of Icarus, or switch to the free version of Modelsim.

**Comment by potentialventures** [comment] 2015-02-08 09:39
Not a bug in Cocotb, closing.

**Closed by potentialventures** 2015-02-08 09:39 UTC
